DROP DATABASE IF EXISTS tracker;

CREATE DATABASE tracker;

USE tracker;


CREATE TABLE tasks (
id INT NOT NULL AUTO_INCREMENT,
taskDate DATE NOT NULL,
duration INT NOT NULL,
subject VARCHAR(50),
assignment VARCHAR(50),
notes VARCHAR(200),
userID VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

CREATE INDEX userIDX ON tasks (userID);